# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'ap'
gem 'bootsnap', '1.3.2', require: false
gem 'cityhash'
gem 'crack'
gem 'dalli'
gem 'doorkeeper', '5.0.2'
gem 'doorkeeper-grants_assertion', '0.2.0'
gem 'graphql', '1.8.11'
gem 'graphql-batch'
gem 'identity_cache'
gem 'jsonb_accessor'
gem 'koala', '3.0.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '3.11'
gem 'pundit'
gem 'rails', '5.2.1'
gem 'redis'
gem 'rubocop'
gem 'sidekiq'
gem 'wisper'
gem 'wisper-activejob'
gem 'wolverine'

group :development, :test do
  gem 'pry'
  gem 'rspec-rails', '~> 3.8'
end

group :development do
  gem 'annotate'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
